mops, soap, and rags don't clean paint
hrzntal/horizon pull request #1224
Opened 2023-03-08 17:39 UTC by CASEYGUNGEON

## About The Pull Request

Adds a new "Clean Type" and makes common cleaning tools use it, causing them to no longer clean applied paint colors.

## Why It's Good For The Game

Resolves #1199.

## Changelog
:cl:
code: Standard cleaning tools no longer remove paint.
/:cl:

2023-03-08 17:40 UTC, CASEYGUNGEON commented
Have to double-check that I didn't miss any specific cleaning tools.

2023-04-02 20:21 UTC, CASEYGUNGEON commented
should be everything

2023-04-03 02:00 UTC, atakiya requested changes

2023-04-03 02:00 UTC, atakiya commented on code/game/atoms.dm
> +	if((clean_types & CLEAN_TYPE_PAINT) && length(atom_colours) >= WASHABLE_COLOUR_PRIORITY && atom_colours[WASHABLE_COLOUR_PRIORITY])
```suggestion
	if((clean_types & CLEAN_TYPE_PAINT) && (length(atom_colours) >= WASHABLE_COLOUR_PRIORITY) && atom_colours[WASHABLE_COLOUR_PRIORITY])
```
Unsure how BYOND would prioritize this, so let's just be safe and do this 😅

2023-04-08 23:28 UTC, atakiya approved these changes

2023-04-16 18:01 UTC, merged