Luxury bar cruiser
hrzntal/horizon pull request #303
Opened 2021-06-26 02:31 UTC by rhodochrositech

## About The Pull Request
This pull request adds a pre-fixed up whiteship with a dark secret. Designed as an admin-event ship providing a high roleplay environment including a bar bouncer role and captain role, this ship can provide quite an adventure and roleplay experience.

Adds The Barrows, a whiteship with a bar and lounge designed for luxury.
Equipped with:
Identification Cards, Uniforms
Self Defense Weaponry
Fully stocked medical bay
A beautiful 5 star bar
A fine dining experience with a view of open space
A robust security system
Employment Opportunities with wonderful medical benefits
A couple of interesting easter eggs

## Why It's Good For The Game
Adds content, environment, and a great idea for low population controlled antaggery that guides proper escalation (Debt type) while constructing it around the concept of a job.
![barrows](https://user-images.githubusercontent.com/86504079/123499475-22aee580-d605-11eb-83ab-7d32d1a59fc3.png)

## Changelog
:cl:
Adds Whiteship, The Barrows V1.
/:cl:

2021-06-26 08:48 UTC, atakiya requested changes
A few codestyle issues only.

---
If you use vscode or anoher editor with plugin support, you can install an extension/plugin that can read `.editorconfig` files to automatically fix code formatting without manual intervention.

2021-06-26 08:48 UTC, atakiya commented on code/datums/shuttles.dm
> +	name = "The Barrows"
```suggestion

/datum/map_template/shuttle/barrow
	port_id = "whiteship"
	suffix = "the_barrows"
	name = "The Barrows"

```
newlines around blocks please.

2021-06-26 08:48 UTC, atakiya commented on code/game/area/areas/shuttles.dm
> +	name = "The Barrows Bar"
```suggestion

/area/shuttle/barrow
	name = "The Barrows"
	requires_power = FALSE
	area_limited_icon_smoothing = /area/shuttle/barrow

/area/shuttle/barrow/helm
	name = "The Barrows Helm"

/area/shuttle/barrow/medbay
	name = "The Barrows Medbay"

/area/shuttle/barrow/bar
	name = "The Barrows Bar"
```
As well.

2021-06-26 08:48 UTC, atakiya commented on code/modules/shuttle/white_ship.dm
> +	build_path = /obj/machinery/computer/shuttle/barrow
```suggestion
	build_path = /obj/machinery/computer/shuttle/barrow

```
EOL on newline.

2021-06-26 11:01 UTC, rhodochrositech commented on code/modules/shuttle/white_ship.dm
> +	build_path = /obj/machinery/computer/shuttle/barrow
Thank you - resolving now. Sending in for review in a moment!

2021-06-27 06:03 UTC, atakiya approved these changes
Changes applied.
Changelog fixed.
CI passed.

Good to go 🚀

2021-06-27 06:04 UTC, merged