Supercruiser Aggregeddon and Mezzeriah
hrzntal/horizon pull request #341
Opened 2021-07-01 21:57 UTC by rhodochrositech

## About The Pull Request

## Why It's Good For The Game

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2021-07-02 04:15 UTC, atakiya commented
> balance: Made the softsuit HRV FoxCat not slow the user down as it is a thin suit.

For the future:
**Please do not include balance changes for something completely different in the same PR**

2021-07-03 00:36 UTC, atakiya requested changes
Update changelog please.

2021-07-03 00:38 UTC, rhodochrositech commented
> Update changelog please.

Complete

2021-07-03 00:45 UTC, atakiya approved these changes

2021-07-03 00:46 UTC, merged