Small trader tweaks
hrzntal/horizon pull request #370
Opened 2021-07-04 19:45 UTC by rhodochrositech

## About The Pull Request

## Why It's Good For The Game

## Changelog
:cl:
add: Adds new trader, the Farming Apprentice, who sells foods (Wheat, Corn) and livestock (Chickies, Cows, Goats)
add: Adds a new trader, the Atmospheric trader, who sells internal items (Plasmaman, Vox, and tiny blue atmos can internals)
add: Adds a mining conscription kit to the mineral buyer to have access to equipment
add: Adds a budget insul for over half the price of a vendor insul, and grey bull (Shock Protection) to the Pharmacy
/:cl:

2021-07-04 21:00 UTC, CypressBz commented
I love this PR, Great work!

2021-07-04 21:24 UTC, rhodochrositech commented
> I love this PR, Great work!

tysm!!

2021-07-04 22:55 UTC, atakiya requested changes
One content issue.
Else just code styling

Also I oughta slap an autoformatter on this shit at some point 😄
Don't worry about the other code you didn't do but is indented wrongly.. gonna do that later on with a pass after finishing up my editor plugin..

2021-07-04 22:55 UTC, atakiya commented on code/modules/trading/traders/food.dm
> +	possible_origins = list("Uncle Ben's", "Manure Mounds", "Farmzilla", "Pepperidge Farms", "Johnson's Grand Animal Emporium", "Feral Farms", "Little Taste o' Neo-Italy", "Pizza Gestapo")
```suggestion
	possible_origins = list("Uncle Ben's", "Manure Mounds", "Farmzilla", "Pepperidge Farms", "Johnson's Grand Animal Emporium", "Feral Farms", "Little Taste o' Neo-Italy")
```
While I don't particularly care much, let's rather not.

2021-07-04 22:55 UTC, atakiya commented on code/modules/trading/traders/food.dm
> +				"insult_bad"        = "Y'all really wanna start all this? I'll get my employers on the line and run ya outta fucking town!")
```suggestion
	speech = list(
		"hail" = "Hello! Welcome to ORIGIN, may I take your order?",
		"hail_deny" = "Beeeep... I'm sorry, your connection has been severed.",

		"trade_complete" = "Welcome to ORIGIN!",
		"trade_no_goods" = "Let's see what we're working with...",
		"trade_not_enough" = "This is a prime cut of steak you know. Do you know how much it costs to raise a cow? Do you know how many medals this beautiful animal -",
		"how_much" = "This here animal will run ya VALUE in hard cash.",

		"compliment_deny" = "At least let me take a shower first.",
		"compliment_accept" = "Mighty fine of you, care to roll in the hay in a bit?",
		"insult_good" = "Knock eet the fuck off! *Racks shotgun*.",
		"insult_bad" = "Y'all really wanna start all this? I'll get my employers on the line and run ya outta fucking town!",
	)
```
*Y'all gonna make me scream with the list formatting..*
Also, while space-aligned indents like that are nice, they fuck up a lot with different editors and so on, better to avoid.
Proper editors have plugins to automatically do this, so please do not get a habit of doing this.

2021-07-04 22:55 UTC, atakiya commented on code/modules/trading/traders/food.dm
> +								/datum/sold_goods/pumpkin = 100)
```suggestion
	possible_sold_goods = list(
		/datum/sold_goods/cow = 100,
		/datum/sold_goods/goat = 100,
		/datum/sold_goods/chicken = 100,
		/datum/sold_goods/wheat = 100,
		/datum/sold_goods/corn = 100,
		/datum/sold_goods/pumpkin = 100,
	)
```

2021-07-04 22:55 UTC, atakiya commented on code/modules/trading/traders/goods.dm
> +		)
```suggestion
		/datum/sold_goods/emergency_oxygen = 100,
	)
```

2021-07-04 22:57 UTC, rhodochrositech commented on code/modules/trading/traders/food.dm
> +	possible_origins = list("Uncle Ben's", "Manure Mounds", "Farmzilla", "Pepperidge Farms", "Johnson's Grand Animal Emporium", "Feral Farms", "Little Taste o' Neo-Italy", "Pizza Gestapo")
LOL. That is actually something i missed deleting, that's a name of a shop from the pizza seller. I didn't write that one in, i merely forgot to delete it - thank you for pointing it out

2021-07-04 22:59 UTC, atakiya commented on code/modules/trading/traders/food.dm
> +	possible_origins = list("Uncle Ben's", "Manure Mounds", "Farmzilla", "Pepperidge Farms", "Johnson's Grand Animal Emporium", "Feral Farms", "Little Taste o' Neo-Italy", "Pizza Gestapo")
Was informed those were leftovers from a copy.

2021-07-04 23:01 UTC, atakiya approved these changes

2021-07-04 23:01 UTC, rhodochrositech commented
You're gonna have to get on azarak about that one, maybe 'Pizza Police'?

2021-07-04 23:03 UTC, atakiya commented
> You're gonna have to get on azarak about that one, maybe 'Pizza Police'?

Yeah that could work. Cc @Azarak

2021-07-04 23:49 UTC, atakiya commented
Gonna test merge this for the next round.

2021-07-05 00:26 UTC, Azarak commented
Remove unused and commented out code (the one about the bought grown foods). Also, mind renaming the `binsuls` to `insuls`? I couldn't figure out what it was on the first glance. Corn being for 100 is a bit steep imo, lower it down?

2021-07-05 01:54 UTC, rhodochrositech commented
> Remove unused and commented out code (the one about the bought grown foods). Also, mind renaming the `binsuls` to `insuls`? I couldn't figure out what it was on the first glance. Corn being for 100 is a bit steep imo, lower it down?

I named the Budged Insuls Binsuls because they're budget insuls, should I name them to 'budget_insuls'?

Additionally, Corn is expensive because corn oil can turn into nitroglycerin.

Removing the comment.

2021-07-05 02:49 UTC, Azarak commented
OH they're budgets. Well I dont think budgets should cost that much, normal insuls almost cost that much in the normal vendor I think?

2021-07-05 02:56 UTC, Azarak commented on code/modules/trading/bought_goods/goods.dm
> +	trading_types = list(/obj/item/food/grown = TRADER_SUBTYPES)
unused code still?

2021-07-05 02:58 UTC, rhodochrositech commented on code/modules/trading/bought_goods/goods.dm
> +	trading_types = list(/obj/item/food/grown = TRADER_SUBTYPES)
ty for pointing that out, missed that one

2021-07-05 03:11 UTC, Azarak commented on code/modules/trading/traders/goods.dm
>  	target_sold_goods_amount = 5
```suggestion
	target_sold_goods_amount = 7
```
Up this by a bit to make sure the tools and ores are reliably showing?

2021-07-05 03:13 UTC, Azarak approved these changes

2021-07-05 03:14 UTC, merged