Fixes Corporate Sofa sprites
hrzntal/horizon pull request #692
Opened 2022-01-15 06:40 UTC by KathrinBailey

## About The Pull Request
• Attempts to port https://github.com/tgstation/tgstation/pull/62417 (my own PR) via cherry picking across repos
• Fixes the rear-facing sprites of the sofas and generally tidies them up, so they don't look bad heck.

## Why It's Good For The Game
Upgraded visuals.

## Changelog
:cl:
fix: Corporate sofa sprites are no longer wonky.
/:cl:

2022-01-15 06:50 UTC, MissFox0810 submitted a review, later dismissed
Please make a seprate PR porting the benches as i know a few people would like that.
Will accept this Icon change for the sofas to also include the bench icons.

2022-01-15 07:07 UTC, KathrinBailey commented
I'm so so sorry
![image](https://user-images.githubusercontent.com/53862927/149612964-f354835b-ffcf-48ce-a48a-14ffab38cf55.png)
I don't dismiss it, Github is lying.
I treasure it. I'm not as ungrateful as this is making me sound.

2022-01-15 10:56 UTC, Azarak commented
This PR removes the ability of the linen bins to be able to handle towels aswell as a linen bin subtype that starts with towels

2022-01-15 23:08 UTC, MissFox0810 commented
Changing to draft untill this is ready for review

2022-01-16 05:50 UTC, MissFox0810 commented
Adding as a TM due to some core code changes. and potential better solutions.

2022-01-16 05:50 UTC, atakiya commented
![image](https://user-images.githubusercontent.com/6952402/149648919-1f1816d7-0512-40fe-837c-9c46e4e39304.png)
i did no such thing >:(

2022-01-16 09:21 UTC, Azarak commented on code/game/objects/structures/bedsheet_bin.dm
> +			B = new /obj/item/bedsheet(loc)
```suggestion
			B = new spawned_sheet(loc)
```

2022-01-16 09:21 UTC, Azarak commented on code/game/objects/structures/bedsheet_bin.dm
> +		var/obj/item/bedsheet/B
```suggestion
		var/obj/item/B
```

2022-01-17 11:14 UTC, Azarak approved these changes

2022-01-17 11:17 UTC, atakiya requested changes
Useless comments are not needed.

2022-01-17 11:17 UTC, atakiya commented on code/game/objects/structures/beds_chairs/bed.dm
> +//Double Beds, for luxurious sleeping, i.e. the captain and maybe heads- if people use this for ERP, send them to skyrat
```suggestion
```

2022-01-17 11:17 UTC, atakiya commented on code/game/objects/structures/beds_chairs/sofa.dm
> +// Ported from Skyrat
```suggestion
```

2022-01-17 11:18 UTC, Azarak commented
Oh I didn't even notice those comments, yeah remove them

2022-01-18 04:53 UTC, atakiya approved these changes
Good from my side.

2022-01-21 18:54 UTC, merged