Variable Viewport & AI, PAI Hud Makeover
hrzntal/horizon pull request #758
Opened 2022-01-28 05:02 UTC by nevimer

todo: bugfixes

## About The Pull Request

This brings the variable based viewport from my fork to upstream. Variable Viewport is originally a port from nebula, heavily modified to work with TG forks. 

## Demo Video

https://streamasaurus.com/sharing/dreamseeker_jhTcb8yvQm.mp4

## Why It's Good For The Game

Quality of life, makes the game behave smartly with screen resolution, DPI scaling, odd aspect ratios, chat box sizes without compromises, etc. server admins can configure max view limits with two variable edits in the main file. I can't figure out how to make the serverpref config work, so help on that would be appreciated!

## Changelog
:cl:
add: Variable Viewport, a scaling GUI
add: new AI and PAI HUD layout
add: new DPI and scaling method options added next to file menu
del: Removed old things
qol: Variable based viewport - GUI and HUD now scales to DPI and elements
qol: The GUI can now handle odd sized viewports and odd aspect ratios natively
balance: users can potentially see further if config options allow it
code: new client procs for viewport scaling
refactor: view scaling has changed, defines have changed to TOP,LEFT,RIGHT,BOTTOM over cardinals
refactor: the skin.dmf has been touched dramatically
config: config file options for max view limits added
admin: new variables for view limits and last view limits (debug)
server: view range is a no longer one of two values
/:cl:

2022-01-28 16:24 UTC, atakiya requested changes
All right, let's do this.

First off, linting - we don't use relative proc paths in this codebase as that can cause confusion and lowers readability. DM-langserver will also poke about this as seen below.
![image](https://user-images.githubusercontent.com/6952402/151581237-f6f966f3-2069-4f06-b6e8-7d50253c0463.png)

2022-01-28 16:24 UTC, atakiya commented on code/modules/client/client_viewport.dm
> +	verb/SetWindowIconSize(var/val as num|text)
```suggestion
/client/verb/SetWindowIconSize(var/val as num|text)
```

2022-01-28 16:24 UTC, atakiya commented on code/modules/client/client_viewport.dm
> +	verb/OnResize()
```suggestion
/client/verb/OnResize()
```

2022-01-28 16:24 UTC, atakiya commented on code/modules/client/client_viewport.dm
> +	verb/force_onresize_view_update()
```suggestion
/client/verb/force_onresize_view_update()
```

2022-01-28 16:24 UTC, atakiya commented on code/modules/client/client_viewport.dm
> +	verb/show_winset_debug_values()
```suggestion
/client/verb/show_winset_debug_values()
```

2022-01-28 16:24 UTC, atakiya commented on code/modules/client/client_viewport.dm
> +	verb/fix_viewport()
```suggestion
/client/verb/fix_viewport()
```

2022-01-28 17:42 UTC, atakiya requested changes

2022-01-28 17:42 UTC, atakiya commented on code/modules/client/client_viewport.dm
> +			last_view_y_dim = config.lock_client_view_y || clamp(ceil(text2num(copytext(winsize_string,findtext(winsize_string,"x")+1,0)) / divisor), 15, config.max_client_view_y || 41)
Magic numbers?
What's 15, what's 41 in this context?
Please use temporary defines, or code comments to explain those values.

2022-01-28 17:42 UTC, atakiya commented on code/modules/client/client_viewport.dm
> +	var/obj/skybox/skybox
Non-used variable?

2022-01-28 17:42 UTC, atakiya commented on code/modules/client/client_procs.dm
> +	change_view(getScreenSize(prefs.widescreenpref)) // Danger! Ugly hack to avoid a bug!
What bug?
Could this be elaborated on in code comments if this is important enough for a comment?

2022-01-28 17:42 UTC, atakiya commented on code/_onclick/hud/screen_objects.dm
> +	screen_loc = "CENTER-7,CENTER-7"
What would happen with a non-widescreen (or widescreen) splash in this position?
Currently, widescreen splashes are cut off on the right side in square-mode clients.

My assumption is, this would center the splash and cut it off from both sides, correct?

2022-01-28 17:47 UTC, nevimer commented
> ## Some words
> - 👍 I do like that the HUD is decoupled from the view
> - 👍 Nice UI layout for AI and pAI
> - 👎 This removes the ability to use square-mapview and **forces** widescreen
> - HUD size is still locked with overall tile size (not sure if this is adjustable tbh, but just mentioning it)
> - 👎 This does not add a new scaling option, this merely moves the options from the HTML option UI to the BYOND win32 UI.
> - 👎 This does not have any DPI settings what-so-ever. Please remove mentions of those from your changelog. See below.
> 
> #### No DPI scaling
> Tested on `514.1578`, resolution of `2560x1440`
> | Your code | Horizon Production |
> | ---- | ---- |
> | <details><summary>100% Scaling</summary> ![image](https://user-images.githubusercontent.com/6952402/151591464-a41b7d54-a4c0-41a5-8914-ea24a718baf8.png) </details> | <details><summary>125% Scaling</summary> ![image](https://user-images.githubusercontent.com/6952402/151592537-b436b772-f9bb-441a-97f2-82f2904ebc4c.png) </details> |
> 
> #### Buggy inventory UI
> Certainly should not be floating off like that.
> <details>
> <summary>Image, click here to view</summary>
> 
> ![image](https://user-images.githubusercontent.com/6952402/151594693-7734560e-855f-4c21-8b50-1ca7ba1367c6.png)
> 
> </details>
> 
> ## Conclusion
> Sorry to say, but aside of the decoupled HUD from viewport, **which is great!** and the updated HUD layouts, this does not fix anything else and only moves some options around currently.

By default, the code chooses 64x64 icon scaling, a good preset for 1080p. The user needs to set their size in the top left drop down menu, which doesn't look like it was done in your example. If you want square, an option can be added. The issue with inventory UI is a tg specific issue that does not appear in other codebases I have ported this to. Please allow me to demonstrate how to use it and why the massive changelog was important to document how it worked when I get off work.

2022-01-28 17:47 UTC, atakiya commented
Please mark this as ready to review once this is ready again! :heart:

2022-01-28 17:54 UTC, atakiya commented
> Please allow me to demonstrate how to use it and why the massive changelog was important to document how it worked when I get off work.
> 
Feel free to do so at your leisure, no pressure!


I'm also aware of the settings and have toyed around with them (and increasing/decreasing the limits).
And for the changelog, again, that part is player facing, developer information should be in markdown README's, or code comments / dmdoc format.

The changelog presented previously and currently is still too technical for the average user. If you wish I can reword one when we're done with all adjustments and so on!

2022-01-28 17:56 UTC, nevimer commented
I'll remove the limits for PR demonstration purposes and add more icon sizes for the dropdown menu to avoid sending clients to type verbs and arguments.

try 

"SetWindowIconSize 84" in your command bar" for an in between example of scaling.

2022-01-28 18:01 UTC, Azarak commented on code/modules/client/client_viewport.dm
> +#define ceil(x) (-round(-(x)))
Why does this exist?
If I'm not mistaken this is the same as `round()`
A ceiling macro already exists `CEILING(float, round_to)` (arg 2 usally `1`)

2022-01-28 18:05 UTC, nevimer commented on code/modules/client/client_viewport.dm
> +#define ceil(x) (-round(-(x)))
if it doesn't exist, the code complains about undefined procs.

2022-01-28 18:40 UTC, atakiya commented
> I wasn't aware of how BYOND interacted with windows DPI scaling, so I presumed it worked how it does (Janky) most other games. So yeah, it does not work how I thought it would and the viewport completely disregards windows settings (probably a good thing, it's kinda blurry when it does it, or sends games off screen in certain cases).
>

Blurry or offscreen windowes from scaling only happen with applications that have missing or bad scaling support.

BYOND actually ***does*** scale properly with the DPI, but yeah the mapview is not adjusted as that is handled by BYOND internally, and neither does BYOND expose the windows DPI scale to dreammaker code as far as I know.

2022-01-28 19:02 UTC, atakiya commented on code/datums/components/storage/storage.dm
> +	boxes.screen_loc = "LEFT+[tx],BOTTOM+[ty] to LEFT+[mx],BOTTOM+[my]"
```suggestion
	boxes.screen_loc = "LEFT+[tx]:,BOTTOM+[ty] to LEFT+[mx],BOTTOM+[my]"
```
Removed the colon there accidnetally, this is most likely the culprit for the storage UI bug.

2022-01-28 20:58 UTC, Azarak commented on code/modules/client/client_viewport.dm
> +#define ceil(x) (-round(-(x)))
But this doesn't even do what a ceiling function does.
And we have a macro for a ceiling function which I just laid out for you.

2022-01-29 03:15 UTC, nevimer commented on code/modules/client/client_procs.dm
> +	change_view(getScreenSize(prefs.widescreenpref)) // Danger! Ugly hack to avoid a bug!
A while back I posted a video of it on discord asking for help. Basically, if you don't start 15x15 when entering a mob, all sorts of visual weirdness starts literally cropping up from the bottom right corner. It's most notable as a crop to all sprites originating at the lower right corner of each tile, and it only happens here... weird to explain, and it's not the click catcher. 

So, any instance of resetting to 15x15 eliminates the bug in exchange for a flicker when login is called. Also, I added a manually calling proc for this too in case it does show up.

 You can replicate this by having a wider than 15x15 view and reconnecting, then shrinking your view.

2022-01-29 03:17 UTC, nevimer commented on code/modules/client/client_viewport.dm
> +	var/obj/skybox/skybox
Part of the original implementation, might be able to be trimmed. I recall it freaking out without it, given it adjusts the parallax? Memory is foggy.

2022-01-29 03:19 UTC, atakiya commented on code/modules/client/client_viewport.dm
> +	var/obj/skybox/skybox
This doesn't do anything. It literally just assigns an `/obj` called skybox.
There's no `/obj/skybox` type on this codebase.
This also is not used anywhere in the code below.

2022-01-29 03:21 UTC, nevimer commented on code/_onclick/hud/screen_objects.dm
> +	screen_loc = "CENTER-7,CENTER-7"
You would think it would, and I thought it would too! But in actuality, nothing changes since the starting position for the skybox is the center of a 15x15 grid on a z level with a block holding the logo as a sprite, what this does is prevent the image from starting in the bottom left of that area and pushing it to the center since your view is always centered. On sprites that are bigger than 480x480, it behaves like a center-right align given that the sprite cannot be off the z-level(?)

2022-01-29 03:22 UTC, nevimer commented on code/modules/client/client_viewport.dm
> +	var/obj/skybox/skybox
Probably safely removable then. It's a bay thing leftover.

2022-02-19 02:06 UTC, nevimer commented
Going to try to find time to work on this soon (potentially this week). Been on hold due to reasons.

2022-04-20 21:02 UTC, atakiya commented
I don't see us using most of the features this PR adds.
The QoL improvements to HUD alignment and such are welcome, variable viewport and such are not.

You can either reopen this PR and align it to only contain QoL changes, or reopen a new one, if you wish that is.
Closing for now due to the above + inactivity.

2022-04-20 21:02 UTC, closed without merging

2022-04-21 14:36 UTC, nevimer commented
I'm still here.

2022-04-21 14:39 UTC, nevimer commented
If you don't appreciate the time people take to improve things in the game, then you don't deserve anything at all.

2022-04-21 16:15 UTC, atakiya commented
Sorry but just because you make something doesn't mean it has to be included.

We mentioned multiple times that the variable viewport feature is not something we require or want.
We haven't employed you, neither have we paid you, begged you or otherwise coerced you to spend your time on this. Giving us an attitude like this is unprofessional and not welcome here.

2022-04-21 21:43 UTC, nevimer commented
> Sorry but just because you make something doesn't mean it has to be included.
> 
> We mentioned multiple times that the variable viewport feature is not something we require or want.
> We haven't employed you, neither have we paid you, begged you or otherwise coerced you to spend your time on this. Giving us an attitude like this is unprofessional and not welcome here.

No where in any review did anyone say they didn't want this. Sorry, but I checked multiple times to ensure I wasn't wrong and have come to the conclusion you are either misremembering, seeing something I am not, or gaslighting me.

I spent hours working on this back when it was created, and it was torn apart like tigers catching prey. I feel incredibly disrespected and ultimately disappointed in this whole process. 

Your right, I am not a "professional coder" - I am a person who wants to improve the game. If this is how you treat contribution, count me out.

2022-04-21 23:19 UTC, atakiya commented
as per [my previous comment](https://github.com/hrzntal/horizon/pull/758#issuecomment-1024449017) 

And I've mentioned it before as well.
![image](https://user-images.githubusercontent.com/6952402/164563585-e3b2d651-ff68-4ecb-933e-8c51532b5cd6.png)

I apologize if I didn't directly tell you "no we do not want *this* feature", though I *remember* doing so, but I had a lot going on the past months so it might be a wrong memory - in any case, gaslighting you is **not** my intention.

I have also not said that this *entire* PR is useless, I've only said the variable viewport is something we do not require.
But if removing that feature comes down to you not wanting to adjust the PR towards it, then there's nothing we can do, or should expect to be done - this is your decision, not anyone elses.

And again, we're not required to merge *any* PR. And as an outside contributor you have to understand that we **can** and **may** close **any PR** for **any reason**.
That does not mean that we do not appreciate the work done and time invested, but is a simple risk from an OSS development cycle like this, and exists in every other open source repository.

I apologize for any inconveniences this may have caused.