Ports reinforced glass tables from TG#61153
hrzntal/horizon pull request #815
Opened 2022-02-01 11:18 UTC by KathrinBailey

## About The Pull Request
• Port of https://github.com/tgstation/tgstation/pull/61153

## Why It's Good For The Game
New tables or glass tables!
Since these new tables are a subtype of reinforced tables, they don't shatter. I messed around doing some checks for `obj_integrity` until I realised this.

## Changelog
:cl: QuarianCommando
add: Added five new table variants - Plasmaglass, Reinforced Plasmaglass, Reinforced Glass, Plastitanium Glass, and Titaniumglass.
/:cl:

2022-02-01 14:57 UTC, MissFox0810 requested changes

2022-02-01 14:57 UTC, MissFox0810 commented on code/game/objects/items/stacks/sheets/glass.dm
> +	tableVariant = /obj/structure/table/glass/plasmaglass
```suggestion
	material_flags = MATERIAL_NO_EFFECTS
	tableVariant = /obj/structure/table/glass/plasmaglass
	window_type = /obj/structure/window/plasma/fulltile
```
This like looks like it was removed during cherrypick, and Unsure what the mat flag was changed, so suggested it back in.

2022-02-01 16:55 UTC, atakiya commented
> 🆑 QuarianCommando
> expansion: Added five new table variants - Plasmaglass, Reinforced Plasmaglass, Reinforced Glass, Plastitanium Glass, and  Titaniumglass.
> /🆑
>
we do not have an `expansion` changelog type.

2022-02-03 08:17 UTC, MissFox0810 approved these changes

2022-02-03 08:17 UTC, merged