Removes gibbing from Heretic Sacrifices
hrzntal/horizon pull request #838
Opened 2022-02-06 05:01 UTC by AtoriBirb

## About The Pull Request

Does as it says, removes gibbing from heretic sacrificing, cause less RR is better.

## Why It's Good For The Game

More roleplay friendly, and ya know.. if we ever decide to use it, would be good. Wink wonk.

## Changelog
:cl:
code: removes the gib call from heretic sacrifice
/:cl:

2022-02-06 06:24 UTC, atakiya requested changes
1. This would be better if it was properly replaced with something like dropping organs or similar.
Something that breaks the body without removing it (as gibbing does).
2. Please do not do "Horizon Edit" comment-outs like on other codebases, we do not support this kind of style - git blame is more than enough and this kind of style just adds more noise than is needed.

For youknowhat, this change can and will be implemented on an injection-level, if the above is not possible to do in time.

2022-02-06 07:02 UTC, AtoriBirb commented
> 1. This would be better if it was properly replaced with something like dropping organs or similar.
>    Something that breaks the body without irreversibly removing it (as gibbing does).
> 2. Please do not do "Horizon Edit" comment-outs like on other codebases, we do not support this kind of style - git blame is more than enough and this kind of style just adds more noise than is needed.
> 
> For youknowhat, this change can and will be implemented on an injection-level, if the above is not possible to do in time.

So this is basically what Skyrat has. A gut spillage and so.

2022-02-06 07:39 UTC, atakiya requested changes

2022-02-06 07:39 UTC, atakiya commented on code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
> +			new /obj/effect/gibspawner/generic(get_turf(current_target))
```suggestion
			current_target.spawn_gibs()
```
There's a proc that does this decently enough

2022-02-06 07:40 UTC, atakiya commented on code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
> +			current_target.adjustBruteLoss(250)
```suggestion
			// 200 + organ spill will give the target about ~2-3 seconds of near-death experience
			current_target.adjustBruteLoss(200)
			current_target.spill_organs()
```
I think this would work better:
- the swap makes sure the target either dies, or is very close to dying BEFORE all their organs suddenly fall out.
- The adjustment down to 200 from 250 will give the target a few little seconds before dying
- The above will also add a few other damage types other than brute due to missing lung & liver for the few seconds

Feel free to chime in with your thoughts on this,
if this would be odd in the context of how heretic works - i haven't played as one myself yet - just bump it back to 250 for instant death :-)

2022-02-06 07:56 UTC, AtoriBirb commented
It's not important that they die, just that they have no memory of being.. you know, sacrificed to a eldritch deity and all that.

2022-02-07 04:43 UTC, atakiya reviewed
Oh, after reading the rune activation proc, I understand now. The target has to already be dead for the sacrifice to work, I assume the brute damage then is just for the looks.

Adjusting the damage down to 150 then because there's no reason for this to be higher, it just makes any damage that was already caused for the target to be even more severe.
Could even cut it out completely, but I think having the sacrifice cause some body damage (and the organ spill happening) makes more sense if theres a bit more hurty

2022-02-07 04:43 UTC, atakiya commented on code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
> +			current_target.adjustBruteLoss(200)
```suggestion
			current_target.adjustBruteLoss(150)
```

2022-02-07 08:13 UTC, AtoriBirb commented
Yeah cause literally the obj it to not take someone out for super long as a result of the sacrifice. Them being dead is pretty much enough.

2022-02-07 08:18 UTC, AtoriBirb commented
I've been watching this over on TG where they have a whole different 'sacrifice', where you get sent to a shadow arena to basically fight for your life for a second chance.
https://github.com/tgstation/tgstation/pull/64658
We'll see how that goes though, for now I think this is good.

2022-02-07 08:21 UTC, atakiya commented
> I've been watching this over on TG where they have a whole different 'sacrifice', where you get sent to a shadow arena to basically fight for your life for a second chance. [tgstation/tgstation#64658](https://github.com/tgstation/tgstation/pull/64658) We'll see how that goes though, for now I think this is good.

Oh, that is.. well, I like the base idea. Active content for players vs being dead and passive. Yeah, something like that is what we want to push towards.
After all, we're here to play a game, and there are *enough* situations where you WILL have to wait until being back in the game, so I'm all for stuff like this in the future. Nice find!

2022-02-07 08:22 UTC, merged