Adds a bunch more wing/moth wing/arm wing/leg wing options
hrzntal/horizon pull request #981
Opened 2022-05-26 02:44 UTC by AtoriBirb

## About The Pull Request

So that was a pain in the ass to do, but I did it. I ported over a bunch of wings from SR. The way they were formatted was several FRONT/BEHIND sections had three different versions for primary/secondary/tertiary colors, but I don't think we have that capability here so I combined them all to take after the primary body's color, like all the other available wings.

## Why It's Good For The Game

More wing options woo! Harpy gang can finally happen now.

## Changelog
:cl:
imageadd: Several new wing sprites
/:cl:

2022-05-26 02:48 UTC, Azarak commented on code/modules/mob/dead/new_player/sprite_accessories/wings.dm
> +	return FALSE
What's this for?

2022-05-26 02:49 UTC, Azarak commented on code/modules/mob/dead/new_player/sprite_accessories/wings.dm
> +	center = TRUE
Put the wings that use another icon dimensions under its own subtype, perhaps `/datum/sprite_accessory/wings/mammal/wide` So that the previous icons that fit in 32x32 dont need to be modified

2022-05-26 03:06 UTC, AtoriBirb commented on code/modules/mob/dead/new_player/sprite_accessories/wings.dm
> +	return FALSE
I'm pretty sure it makes the wings appear on top of suits, instead of under them.

2022-05-26 03:34 UTC, Azarak commented on code/modules/mob/dead/new_player/sprite_accessories/wings.dm
> +	return FALSE
This is an override of the parent proc for determining whether the wings are hidden or not, and this one looks ideal to how the moth ones work, and is really not nessecary. The parent proc checks if someone has a suit and is trying to hide wings, then it will hide the wings
```
/datum/sprite_accessory/wings/is_hidden(mob/living/carbon/human/H, obj/item/bodypart/HD)
	if(H.wear_suit && H.try_hide_mutant_parts)
		return TRUE
	return FALSE
```
It's fine to remove this proc override

2022-05-28 00:14 UTC, Azarak commented
But previously there weren't any wings that required the new dimension right? All the new wings will have to be under that `/wide` subtype in their own icon file and it'll be fine.

2022-05-28 05:01 UTC, Azarak commented on code/modules/mob/dead/new_player/sprite_accessories/wings.dm
> +/datum/sprite_accessory/wings/mammal/wide/top/harpywings_top
What's the `/top/` subtype for? It doesn't change anything in the definitions, remove it.

2022-05-28 05:01 UTC, Azarak commented on code/modules/mob/dead/new_player/sprite_accessories/wings.dm
> +	return FALSE*/
```suggestion
```
Remove unused code

2022-05-28 05:21 UTC, AtoriBirb commented on code/modules/mob/dead/new_player/sprite_accessories/wings.dm
> +	return FALSE*/
hnhh I'm failing, yes I forgot I just had it edited out in my version.

2022-05-28 05:26 UTC, AtoriBirb commented on code/modules/mob/dead/new_player/sprite_accessories/wings.dm
> +/datum/sprite_accessory/wings/mammal/wide/top/harpywings_top
oh well I guess getting rid of that redundant slice of code means it wasn't really necessary anymore. I'll make the change.

2022-05-28 10:00 UTC, Azarak approved these changes

2022-05-28 12:45 UTC, atakiya requested changes

2022-05-28 12:45 UTC, atakiya commented on code/modules/mob/dead/new_player/sprite_accessories/wings.dm
> +/datum/sprite_accessory/wings/moth/featherful // Is actually 'feathery' on upstream
Comments like these do not help much as we don't have any specific upstream.
```suggestion
/datum/sprite_accessory/wings/moth/featherful
```

2022-05-30 03:16 UTC, atakiya approved these changes

2022-05-30 03:16 UTC, merged